// Code generated by "stringer -type ErrCode -linecomment ./global/errcode"; DO NOT EDIT.

package errcode


func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SUCCESS-0]
	_ = x[ERROR - -1]
	_ = x[TOKEN_FAIL-401]
	_ = x[TOKEN_FORBIDDEN-403]
	_ = x[ERROR_PARAMS-1003]
	_ = x[ERROR_LOGIN-1004]
	_ = x[ERROR_NO_LOGIN-1005]
	_ = x[FAILURE-2000]
	_ = x[FAILURE_INSERT-2001]
	_ = x[FAILURE_UPDATE-2002]
	_ = x[FAILURE_DELETE-2003]
	_ = x[FORBIDDEN-4000]
	_ = x[ERROR_SERVER-5000]
	_ = x[FORBIDDEN_SN-4001]
	_ = x[FORBIDDEN_IP-4002]
	_ = x[FORBIDDEN_METHOD-4003]
	_ = x[FORBIDDEN_NO_PERMISSION-4004]
	_ = x[ALARM_CONFIG_TIME_ERROR-4005]
}
